/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DataSwarm {
  export type DatasetStruct = {
    id: BigNumberish;
    storageHash: string;
    metadataURI: string;
    contributor: AddressLike;
    price: BigNumberish;
    validationScore: BigNumberish;
    validationReportHash: string;
    isValidated: boolean;
    totalPurchases: BigNumberish;
    earnings: BigNumberish;
    createdAt: BigNumberish;
  };

  export type DatasetStructOutput = [
    id: bigint,
    storageHash: string,
    metadataURI: string,
    contributor: string,
    price: bigint,
    validationScore: bigint,
    validationReportHash: string,
    isValidated: boolean,
    totalPurchases: bigint,
    earnings: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    storageHash: string;
    metadataURI: string;
    contributor: string;
    price: bigint;
    validationScore: bigint;
    validationReportHash: string;
    isValidated: boolean;
    totalPurchases: bigint;
    earnings: bigint;
    createdAt: bigint;
  };
}

export interface DataSwarmInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "PLATFORM_FEE_BPS"
      | "getAllDatasets"
      | "getDataset"
      | "getTotalDatasets"
      | "hasAccess"
      | "listDataset"
      | "owner"
      | "purchaseDataset"
      | "renounceOwnership"
      | "submitValidation"
      | "transferOwnership"
      | "withdrawEarnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DatasetListed"
      | "DatasetPurchased"
      | "DatasetValidated"
      | "EarningsWithdrawn"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllDatasets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDataset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDatasets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listDataset",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseDataset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitValidation",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEarnings",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllDatasets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDataset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDatasets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listDataset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseDataset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEarnings",
    data: BytesLike
  ): Result;
}

export namespace DatasetListedEvent {
  export type InputTuple = [
    datasetId: BigNumberish,
    contributor: AddressLike,
    storageHash: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: bigint,
    contributor: string,
    storageHash: string,
    price: bigint
  ];
  export interface OutputObject {
    datasetId: bigint;
    contributor: string;
    storageHash: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DatasetPurchasedEvent {
  export type InputTuple = [
    datasetId: BigNumberish,
    buyer: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [datasetId: bigint, buyer: string, price: bigint];
  export interface OutputObject {
    datasetId: bigint;
    buyer: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DatasetValidatedEvent {
  export type InputTuple = [
    datasetId: BigNumberish,
    score: BigNumberish,
    reportHash: string
  ];
  export type OutputTuple = [
    datasetId: bigint,
    score: bigint,
    reportHash: string
  ];
  export interface OutputObject {
    datasetId: bigint;
    score: bigint;
    reportHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsWithdrawnEvent {
  export type InputTuple = [
    datasetId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: bigint,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    datasetId: bigint;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataSwarm extends BaseContract {
  connect(runner?: ContractRunner | null): DataSwarm;
  waitForDeployment(): Promise<this>;

  interface: DataSwarmInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  getAllDatasets: TypedContractMethod<
    [],
    [DataSwarm.DatasetStructOutput[]],
    "view"
  >;

  getDataset: TypedContractMethod<
    [datasetId: BigNumberish],
    [DataSwarm.DatasetStructOutput],
    "view"
  >;

  getTotalDatasets: TypedContractMethod<[], [bigint], "view">;

  hasAccess: TypedContractMethod<
    [datasetId: BigNumberish, buyer: AddressLike],
    [boolean],
    "view"
  >;

  listDataset: TypedContractMethod<
    [storageHash: string, price: BigNumberish, metadataURI: string],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  purchaseDataset: TypedContractMethod<
    [datasetId: BigNumberish],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitValidation: TypedContractMethod<
    [datasetId: BigNumberish, score: BigNumberish, reportHash: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawEarnings: TypedContractMethod<
    [datasetId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllDatasets"
  ): TypedContractMethod<[], [DataSwarm.DatasetStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getDataset"
  ): TypedContractMethod<
    [datasetId: BigNumberish],
    [DataSwarm.DatasetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalDatasets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [datasetId: BigNumberish, buyer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "listDataset"
  ): TypedContractMethod<
    [storageHash: string, price: BigNumberish, metadataURI: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseDataset"
  ): TypedContractMethod<[datasetId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitValidation"
  ): TypedContractMethod<
    [datasetId: BigNumberish, score: BigNumberish, reportHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawEarnings"
  ): TypedContractMethod<[datasetId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DatasetListed"
  ): TypedContractEvent<
    DatasetListedEvent.InputTuple,
    DatasetListedEvent.OutputTuple,
    DatasetListedEvent.OutputObject
  >;
  getEvent(
    key: "DatasetPurchased"
  ): TypedContractEvent<
    DatasetPurchasedEvent.InputTuple,
    DatasetPurchasedEvent.OutputTuple,
    DatasetPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "DatasetValidated"
  ): TypedContractEvent<
    DatasetValidatedEvent.InputTuple,
    DatasetValidatedEvent.OutputTuple,
    DatasetValidatedEvent.OutputObject
  >;
  getEvent(
    key: "EarningsWithdrawn"
  ): TypedContractEvent<
    EarningsWithdrawnEvent.InputTuple,
    EarningsWithdrawnEvent.OutputTuple,
    EarningsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DatasetListed(uint256,address,string,uint256)": TypedContractEvent<
      DatasetListedEvent.InputTuple,
      DatasetListedEvent.OutputTuple,
      DatasetListedEvent.OutputObject
    >;
    DatasetListed: TypedContractEvent<
      DatasetListedEvent.InputTuple,
      DatasetListedEvent.OutputTuple,
      DatasetListedEvent.OutputObject
    >;

    "DatasetPurchased(uint256,address,uint256)": TypedContractEvent<
      DatasetPurchasedEvent.InputTuple,
      DatasetPurchasedEvent.OutputTuple,
      DatasetPurchasedEvent.OutputObject
    >;
    DatasetPurchased: TypedContractEvent<
      DatasetPurchasedEvent.InputTuple,
      DatasetPurchasedEvent.OutputTuple,
      DatasetPurchasedEvent.OutputObject
    >;

    "DatasetValidated(uint256,uint8,string)": TypedContractEvent<
      DatasetValidatedEvent.InputTuple,
      DatasetValidatedEvent.OutputTuple,
      DatasetValidatedEvent.OutputObject
    >;
    DatasetValidated: TypedContractEvent<
      DatasetValidatedEvent.InputTuple,
      DatasetValidatedEvent.OutputTuple,
      DatasetValidatedEvent.OutputObject
    >;

    "EarningsWithdrawn(uint256,address,uint256)": TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;
    EarningsWithdrawn: TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
